"""empty message

Revision ID: ec4767a007da
Revises: 4366239b4800
Create Date: 2021-06-20 13:10:15.776431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4767a007da'
down_revision = '4366239b4800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('past_shows', 'artist_image_link')
    op.drop_column('past_shows', 'artist_name')
    op.drop_column('upcoming_shows', 'artist_image_link')
    op.drop_column('upcoming_shows', 'artist_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming_shows', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('upcoming_shows', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('past_shows', sa.Column('artist_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('past_shows', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
