"""empty message

Revision ID: f6c9f20af178
Revises: fbf801735998
Create Date: 2021-06-14 19:35:47.323752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c9f20af178'
down_revision = 'fbf801735998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PastShow', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('PastShow', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'PastShow', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'PastShow', 'Venue', ['venue_id'], ['id'])
    op.add_column('UpcomingShow', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('UpcomingShow', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'UpcomingShow', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'UpcomingShow', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UpcomingShow', type_='foreignkey')
    op.drop_constraint(None, 'UpcomingShow', type_='foreignkey')
    op.drop_column('UpcomingShow', 'venue_id')
    op.drop_column('UpcomingShow', 'id')
    op.drop_constraint(None, 'PastShow', type_='foreignkey')
    op.drop_constraint(None, 'PastShow', type_='foreignkey')
    op.drop_column('PastShow', 'venue_id')
    op.drop_column('PastShow', 'id')
    # ### end Alembic commands ###
